title: Jim's Blog
description: > # this means to ignore newlines until "baseurl:"
  An IT infrastructure and general technology blog from Jim Walters. An IT Infrastructure technician based in Berkshire.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.techwalters.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jim Walters # add your name
author-img: jim-walters.jpg # add your photo
about-author: I am an IT Infrastructure technician based in Berkshire, UK. I've got a keen interest in all things cloud computing, and technology in general. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vampyrbyte # add your Github handle
social-linkedin: jim-walters-7baa4530 # add your Linkedin handle
social-email: jim@techwalters.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
